-- Create Products Table
CREATE TABLE products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  name TEXT NOT NULL,
  description TEXT,
  price BIGINT NOT NULL, -- Schema shows int8 for price, interesting choice!
  imageURL TEXT,
  category TEXT NOT NULL,
  avaliable BOOLEAN DEFAULT TRUE
);

-- Create Orders Table
CREATE TABLE orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  customer_id BIGINT,
  total_price BIGINT NOT NULL,
  item_details JSON NOT NULL,
  customer_address TEXT,
  customer_phone TEXT,
  payment_method TEXT,
  status TEXT DEFAULT 'pending'
);

-- Seed Products (Note: Prices are int8 in schema, so we use integers)
INSERT INTO products (name, description, price, imageURL, category, avaliable) VALUES
('Classic Cheeseburger', 'Juicy beef patty with cheddar cheese, lettuce, and our secret sauce.', 13, 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&q=80&w=800', 'Main', true),
('Margherita Pizza', 'Fresh mozzarella, tomato sauce, and basil on a crispy crust.', 15, 'https://images.unsplash.com/photo-1604382354936-07c5d9983bd3?auto=format&fit=crop&q=80&w=800', 'Main', true),
('Crispy Chicken Wings', '6 pieces of spicy buffalo wings served with ranch dressing.', 8.99, 'https://images.unsplash.com/photo-1567620905732-2d1ec7bb7445?auto=format&fit=crop&q=80&w=800', 'Sides', true),
('Caesar Salad', 'Fresh romaine, parmesan cheese, croutons, and Caesar dressing.', 10.99, 'https://images.unsplash.com/photo-1550304943-4f24f54ddde9?auto=format&fit=crop&q=80&w=800', 'Sides', true),
('Chocolate Lava Cake', 'Warm chocolate cake with a molten center, served with vanilla ice cream.', 7.50, 'https://images.unsplash.com/photo-1624353365286-3f8d62daad51?auto=format&fit=crop&q=80&w=800', 'Dessert', true),
('Large Iced Latte', 'Creamy espresso brewed with chilled milk and ice.', 4.99, 'https://images.unsplash.com/photo-1517701604599-bb29b565090c?auto=format&fit=crop&q=80&w=800', 'Drinks', true),
('House Lemonade', 'Freshly squeezed lemons with a hint of mint.', 3.50, 'https://images.unsplash.com/photo-1523472721958-978152f4d69b?auto=format&fit=crop&q=80&w=800', 'Drinks', true),
('French Fries', 'Golden and crispy salted fries.', 4.00, 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?auto=format&fit=crop&q=80&w=800', 'Sides', true);
