-- Create Products Table
CREATE TABLE products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  name TEXT NOT NULL,
  description TEXT,
  price DECIMAL(10, 2) NOT NULL,
  image_url TEXT,
  category TEXT NOT NULL,
  available BOOLEAN DEFAULT TRUE
);

-- Create Orders Table
CREATE TABLE orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  customer_id BIGINT,
  total_price DECIMAL(10, 2) NOT NULL,
  item_details JSONB NOT NULL,
  customer_address TEXT,
  customer_phone TEXT,
  payment_method TEXT,
  status TEXT DEFAULT 'pending'
);

-- Seed Products
INSERT INTO products (name, description, price, image_url, category, available) VALUES
('Wagyu Truffle Burger', 'A5 Wagyu beef patty, black truffle aioli, aged cheddar, and caramelized onions on a brioche bun.', 24.50, 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&q=80&w=800', 'Mains', true),
('Saffron Seafood Paella', 'Authentic Spanish rice dish with lobster, tiger prawns, mussels, and saffron-infused broth.', 32.00, 'https://images.unsplash.com/photo-1534080564583-6be75777b70a?auto=format&fit=crop&q=80&w=800', 'Mains', true),
('Wild Mushroom Risotto', 'Creamy Arborio rice with porcini mushrooms, parmesan crisp, and truffle oil drizzle.', 18.75, 'https://images.unsplash.com/photo-1476124369491-e7addf5db371?auto=format&fit=crop&q=80&w=800', 'Mains', true),
('Crispy Tuna Tartare', 'Fresh spicy tuna on crispy rice cakes with avocado mousse and jalapeño.', 16.00, 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&q=80&w=800', 'Starters', true),
('Burrata & Heirloom Salad', 'Fresh burrata cheese, heirloom tomatoes, basil pesto, and balsamic glaze.', 14.50, 'https://images.unsplash.com/photo-1529312266912-b33cf6227e24?auto=format&fit=crop&q=80&w=800', 'Starters', true),
('Molten Gold Lava Cake', 'Rich dark chocolate cake with a molten gold caramel center, served with vanilla bean ice cream.', 12.00, 'https://images.unsplash.com/photo-1624353365286-3f8d62daad51?auto=format&fit=crop&q=80&w=800', 'Desserts', true),
('Matcha Green Tea Tiramisu', 'Japanese twist on the classic, with matcha-soaked ladyfingers and mascarpone cream.', 11.50, 'https://images.unsplash.com/photo-1550617931-e17a7b70dce2?auto=format&fit=crop&q=80&w=800', 'Desserts', true),
('Smoked Old Fashioned', 'Bourbon, maple syrup, angostura bitters, smoked with cherry wood.', 15.00, 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?auto=format&fit=crop&q=80&w=800', 'Drinks', true),
('Yuzu Sparkler', 'Refreshing yuzu citrus with sparkling water and mint.', 6.50, 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&q=80&w=800', 'Drinks', true),
('Artisan Cheese Board', 'Selection of fine cheeses, honey, nuts, and artisanal crackers.', 22.00, 'https://images.unsplash.com/photo-1631379578550-7038263db699?auto=format&fit=crop&q=80&w=800', 'Starters', true);
